development:
  adapter: postgresql
  encoding: unicode
  database: footnote_dev
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: footnote_test
  pool: 5
  
production:
  adapter: postgresql
  encoding: unicode
  database: footnote_production
  pool: 5


